#pragma once
#include <iostream>
#include <atomic>
#include <array>
#include <string>
#include <vector>
#include <list>
#include <map>
#include <set>
#include <memory>
#define _USE_MATH_DEFINES
#include <math.h>
#include <cmath>
#include <complex>
#include <functional>
#include <limits>
#include <stack>
#include <thread>

#include "SFML/Window.hpp"
#include "SFML/Graphics.hpp"
#include "imgui-SFML.h"
#include "imgui.h"
